### ISSUE TITLE
Error while running the container;

### ISSUE THREAD

**Issue by Albin-Roy** [Albin-Roy/ThreatInteL#1]
# docker-compose up
Starting inircrew-project_selenium_1 ... done
Starting inircrew-project_app_1      ... done
Attaching to inircrew-project_selenium_1, inircrew-project_app_1
selenium_1  | 2022-04-18 19:23:04,022 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
selenium_1  | 2022-04-18 19:23:04,024 INFO supervisord started with pid 8
app_1       | Traceback (most recent call last):
app_1       |   File "/app/test.py", line 56, in <module>
app_1       |     CertIn()
app_1       |   File "/app/test.py", line 14, in CertIn
app_1       |     driver = webdriver.Firefox(options=option)
app_1       |   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 181, in __init__
app_1       |     RemoteWebDriver.__init__(
app_1       |   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 269, in __init__
app_1       |     self.start_session(capabilities, browser_profile)
app_1       |   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in start_session
app_1       |     response = self.execute(Command.NEW_SESSION, parameters)
app_1       |   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
app_1       |     self.error_handler.check_response(response)
app_1       |   File "/usr/local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
app_1       |     raise exception_class(message, screen, stacktrace)
app_1       | selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
app_1       | 
inircrew-project_app_1 exited with code 1
selenium_1  | 2022-04-18 19:23:05,026 INFO spawned: 'xvfb' with pid 10
selenium_1  | 2022-04-18 19:23:05,027 INFO spawned: 'vnc' with pid 11
selenium_1  | 2022-04-18 19:23:05,028 INFO spawned: 'novnc' with pid 12
selenium_1  | 2022-04-18 19:23:05,029 INFO spawned: 'selenium-standalone' with pid 13
selenium_1  | Setting up SE_NODE_GRID_URL...
selenium_1  | 2022-04-18 19:23:05,035 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1  | 2022-04-18 19:23:05,035 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1  | 2022-04-18 19:23:05,035 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1  | 2022-04-18 19:23:05,036 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1  | Selenium Grid Standalone configuration: 
selenium_1  | [network]
selenium_1  | relax-checks = true
selenium_1  | 
selenium_1  | [node]
selenium_1  | session-timeout = "300"
selenium_1  | override-max-sessions = false
selenium_1  | detect-drivers = false
selenium_1  | max-sessions = 1
selenium_1  | 
selenium_1  | [[node.driver-configuration]]
selenium_1  | display-name = "firefox"
selenium_1  | stereotype = '{"browserName": "firefox", "browserVersion": "99.0", "platformName": "Linux"}'
selenium_1  | max-sessions = 1
selenium_1  | 
selenium_1  | Starting Selenium Grid Standalone...
selenium_1  | 19:23:05.327 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
selenium_1  | 19:23:05.330 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
selenium_1  | 19:23:05.726 INFO [NodeOptions.getSessionFactories] - Detected 4 available processors
selenium_1  | 19:23:05.758 INFO [NodeOptions.report] - Adding firefox for {"browserVersion": "99.0","se:noVncPort": 7900,"browserName": "firefox","platformName": "Linux","se:vncEnabled": true} 1 times
selenium_1  | 19:23:05.769 INFO [Node.<init>] - Binding additional locator mechanisms: name, relative, id
selenium_1  | 19:23:05.791 INFO [GridModel.setAvailability] - Switching node 3436d258-2d61-479b-ab82-06c81fefb2bd (uri: http://172.19.0.2:4444) from DOWN to UP
selenium_1  | 19:23:05.791 INFO [LocalDistributor.add] - Added node 3436d258-2d61-479b-ab82-06c81fefb2bd at http://172.19.0.2:4444. Health check every 120s
selenium_1  | 19:23:05.880 INFO [Standalone.execute] - Started Selenium Standalone 4.1.3 (revision 7b1ebf28ef): http://172.19.0.2:4444

**Comment by Albin-Roy** [comment]
@DanBrown47

**Comment by DanBrown47** [comment]
Acknowledged will look into it soon

**Comment by DanBrown47** [comment]
@Albin-Roy The issue is coming up due to lack of FireFox installed inside the docker or you have not attached the volume, using -v docker_path:local_system_path_to_firefox

Try this during execution.

Thanks
